environment:
  RENDER: True  #!
  VENV_SEED: 42
  ENV_NAME: Push-v0
  ACTION_DIM: 3
  ACTION_MAG: 1.0
  USE_APPEND: False
  MAX_TRAIN_STEPS: 25 # 5Hz, 10s
  MAX_EVAL_STEPS: 25
  USE_RGB: True
  USE_DEPTH: False
  NUM_ENV_TRAIN: 100
  DATASET: /home/allen/panda/data/private/box/box_100_0.pkl
  CAMERA:
    pos:
      - 0.5
      - 0
      - 0.6
    euler:
      - 0
      - -3.142
      - 1.571
    img_w: 64
    img_h: 64
    aspect: 1
    fov: 70
    max_depth: 0.6

training:
  EVAL: True
  USE_WANDB: False
  DEVICE: cuda:0
  IMAGE_DEVICE: cuda:0
  NUM_CPUS: 2 #!
  SEED: 42
  NAME: push_0_eval
  OUT_FOLDER: /home/allen/panda/result/push_0/eval
  PROJECT_NAME: push
  AGENT_NAME: AgentPush
  SAVE_TOP_K: 20
  SAVE_METRIC: reward
  MAX_SAMPLE_STEPS: 100000
  MEMORY_CAPACITY: 10000
  MIN_STEPS_B4_OPT: 2000
  OPTIMIZE_FREQ: 2000
  UPDATE_PER_OPT: 200
  CHECK_OPT_FREQ: 2
  NUM_EVAL_EPISODE: 10

update:
  EVAL: True
  DEVICE: cuda:0
  BATCH_SIZE: 128
  UPDATE_PERIOD: 1
  ALPHA: 0.05
  LEARN_ALPHA: False
  GAMMA: 0.99
  GAMMA_SCHEDULE: false
  LR_A: 0.001
  LR_Al: 0.001
  LR_C: 0.001
  LR_A_SCHEDULE: false
  LR_Al_SCHEDULE: false
  LR_C_SCHEDULE: false
  TAU: 0.01
  MODE: performance
  ACTOR_PATH: /home/allen/panda/result/push_0/0/model/actor/actor-144000.pth
  CRITIC_PATH: /home/allen/panda/result/push_0/0/model/critic/critic-144000.pth

arch:
  ACTIVATION:
    actor: ReLU
    critic: ReLU
  KERNEL_SIZE:
  - 5
  - 3
  - 3
  STRIDE:
  - 1
  - 1
  - 1
  PADDING:
  - 2
  - 1
  - 1
  N_CHANNEL:
  - 8
  - 16
  - 32
  MLP_DIM:
    actor:
    - 64
    - 64
    critic:
    - 64
    - 64
  APPEND_DIM: 0 #? EE pose
  USE_BN: false
  USE_LN: True
  USE_SM: True  #!